services:
  api:
    build:
      context: .
      dockerfile: dockerfiles/api/Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_started
    ports:
      - "8000:8000"
    command: bash -c "uvicorn src.server.app:get_app --host 0.0.0.0 --port 8000 --factory"

  postgres:
    image: "postgres:15"
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: CMD-SHELL pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql